### ISSUE TITLE
Algorithm change?

### ISSUE THREAD

**Issue by debuti** [victor-oliveira1/ZippyDown#4]
This morning I received this message

```
$python3 ~/tmp/zippyshare_downloader/zippyshare_downloader.py links 
Starting Zippyshare Downloader for http://www66.zippyshare.com/v/VlNZgnnb/file.html...
Traceback (most recent call last):
  File "/home/debuti/tmp/zippyshare_downloader/zippyshare_downloader.py", line 74, in <module>
    dl(line.rstrip())
  File "/home/debuti/tmp/zippyshare_downloader/zippyshare_downloader.py", line 43, in dl
    auth_number = eval(re.findall('\(.*\)', download_link[0])[0])
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
```
Seems like the algorithm changed, I will take a quick look to broaden the report

Thanks

**Comment by debuti** [comment]
To solve this once and for all I'm going to implement a little phantomjs script to fetch the dl link, solving the involved JS of the page. Ill let you know when its ready

**Comment by victor-oliveira1** [comment]
Hi!
Thank you for improve this handy tool!

**Comment by victor-oliveira1** [comment]
Hey, i found a way to always interpret the correct algorithm using selenium:

```
from selenium import webdriver
driver = webdriver.Firefox()
driver.get(URL)
element = driver.find_element_by_id('dlbutton')
url_download = element.get_attribute('href')
print(url_download)


```

**Comment by debuti** [comment]
Nice! So you wont need any dependency again? Is it faster than phantomjs? The last one is very likely :/

**Comment by victor-oliveira1** [comment]
I've made some tests, and using PhantomJS is better, because you don't need a browser window opening everytime :P
I have changed the main code.
Some things still need more work, buut, now it works without worry about algorithm change.
And another thing, i've seen some links from Zippy in this format: zippyshare.com/pd...
I think the URL validation need to use another way :(
Buut, works! :D
